# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="safra",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safra",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safra",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safra",
            name="cultura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.cultura",
            ),
        ),
        migrations.AddField(
            model_name="safra",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "Em andamento"), ("finished", "Finalizada")],
                default="in_progress",
                max_length=32,
            ),
        ),
    ]

