# Generated by Codex on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_safra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cultivar",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cultivar",
            name="cycle",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="cultivar",
            name="maturity",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="cultivar",
            name="region_indicated",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
        migrations.AddField(
            model_name="cultivar",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]

