# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_cultivar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="operacao",
            name="kind",
            field=models.CharField(
                choices=[("credit", "Credito"), ("debit", "Debito"), ("transfer", "Transferencia")],
                default="credit",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="conta",
            name="agencia",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="conta",
            name="saldo_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="conta",
            name="limite",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="conta",
            name="banco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.banco",
            ),
        ),
        migrations.AddField(
            model_name="conta",
            name="produtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.produtor",
            ),
        ),
        migrations.AddField(
            model_name="condicaofinanceira",
            name="dias",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="condicaofinanceira",
            name="parcelas",
            field=models.IntegerField(default=1),
        ),
    ]

