# Generated by Django 5.1.5 on 2026-03-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backuparchive_backupschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backuparchive',
            new_name='core_backup_company_80b936_idx',
            old_name='core_backup_company_created_idx',
        ),
    ]
