# Generated by Django 5.1.6 on 2026-03-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsubscription",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="billingsubscription",
            name="module_code",
            field=models.CharField(
                default="crm",
                help_text="Modulo contratado: erp, crm, power_bi, landing_page",
                max_length=30,
            ),
        ),
    ]
